# Generated by Django 3.2.8 on 2021-10-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_auto_20211028_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsModel',
        ),
    ]
