# Generated by Django 3.2.8 on 2021-10-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20211028_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
