# Generated by Django 3.2.8 on 2021-11-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20211028_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='dateCreation',
            field=models.DateTimeField(null=True),
        ),
    ]
