# Generated by Django 3.2.8 on 2021-11-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_newsmodel_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
